# Generated by Django 3.2 on 2021-04-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Image4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
